// jshint esversion:6
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';

import { useState } from 'react';

import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub} from 'react-icons/ai';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark': ''}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900' >
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:bg-gray-900 dark:text-teal-300'>developedby Rohail</h1>
            <ul className='flex items-center dark:bg-gray-900 dark:text-teal-300'>
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:bg-gray-900 dark:text-teal-300' /></li>
              <li>
                <a href="" className='bg-gradient-to-r from-amber-900 via-teal-400 to-teal-800 text-white px-4 py-2 rounded-md ml-8'>
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-7 '>
            <h2 className='text-5xl py-2 text-amber-900 font-medium md:text-6xl dark:bg-gray-900 dark:text-teal-300'>Muhammd Rohail Omer</h2>
            <h3 className='text-2xl py-1 md:text-3xl dark:bg-gray-900 dark:text-teal-300'>Electrical Engineer and Developer</h3>
            <p className='text-md py-4 leading-7 text-gray-700 md:text-xl max-w-lg mx-auto dark:bg-gray-900 dark:text-teal-300'>Freelancer for providing programming services. Join me below and lets start canvassing.</p>
          </div>
          <div className='text-5xl flex justify-center ga-14 py-2 text-gray-500 dark:bg-gray-900 dark:text-teal-300'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className='relative bg-gradient-to-b  from-amber-900 via-teal-400 to-teal-800 rounded-full w-80 h-80 mt-20 mx-auto my-auto overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} layout="fill" objectFit='cover' />
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:bg-gray-900 dark:text-teal-300'>Services I Offer</h3>
            <p className='text-md py-1 leading-7 text-gray-700 dark:bg-gray-900 dark:text-teal-300'>Since the start of my journey i have been providing servics in Pcb design but now i also provide freelance services in web design and development of E-commerce and small busnisses websites</p>
          </div>
          <div className="flex md:flex-row flex-col">
            <div className="text-center shadow-lg p-8 basis-1/2 rounded-xl my-9 dark:bg-gray-900 dark:text-teal-300">
              <Image src={design} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">Immersive Designs</h3>
              <p className="py-2">Creating immersive desgins for greater experiance</p>
              <h4 className="py-4 text-amber-900 dark:bg-gray-900 dark:text-teal-300">Design Tools I use</h4>
              <p className="text-gray-700 py-1 dark:bg-gray-900 dark:text-teal-300">Figma</p>
              <p className="text-gray-700 py-1 dark:bg-gray-900 dark:text-teal-300">Photoshop</p>
            </div>
            <div className="text-center shadow-lg basis-1/2 p-8 rounded-xl my-9 dark:bg-gray-900 dark:text-teal-300">
              <Image src={code} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:bg-gray-900 dark:text-teal-300">Readable Code</h3>
              <p className="py-2">Tested and Fully readable code</p>
              <h4 className="py-4 text-amber-900 dark:bg-gray-900 dark:text-teal-300">IDE I use</h4>
              <p className="text-gray-700 py-1 dark:bg-gray-900 dark:text-teal-300">Visual Studio Code</p>
            </div>
            <div className="text-center shadow-lg basis-1/2 p-6 rounded-xl my-9 dark:bg-gray-900 dark:text-teal-300">
              <Image src={consulting} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:bg-gray-900 dark:text-teal-300">Consultations</h3>
              <p className="py-2 ">Consult on existing designs and code to make changes to your need</p>
              <h4 className="py-4 text-amber-900 dark:bg-gray-900 dark:text-teal-300">Design Tools I use</h4>
              <p className="text-gray-700 py-1 dark:bg-gray-900 dark:text-teal-300">Figma</p>
              <p className="text-gray-700 py-1 dark:bg-gray-900 dark:text-teal-300">Photoshop</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl pb-1 dark:bg-gray-900 dark:text-teal-300">Portfolio</h3>
            <p className='text-md py-1 leading-7 text-gray-700 dark:text-teal-300'>Since the start of my journey i have been providing servics in Pcb design but now i also provide freelance services in web design and development of E-commerce and small busnisses websites</p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'><Image className='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive" src={web1} /></div>
            <div className='basis-1/3 flex-1'><Image className='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive" src={web2} /></div>
            <div className='basis-1/3 flex-1'><Image className='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive" src={web3} /></div>
            <div className='basis-1/3 flex-1'><Image className='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive" src={web4} /></div>
            <div className='basis-1/3 flex-1'><Image className='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive" src={web5} /></div>
            <div className='basis-1/3 flex-1'><Image className='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive" src={web6} /></div>
          </div>
        </section>
      </main>

    </div>
  )
}
